title: nmfs-opensci-container-images
description: nmfs-opensci-container-images using the Just the Docs theme!
theme: just-the-docs
url: https://michaelakridge-noaa.github.io/
logo: "<img src="https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true" alt="NMFS Open Science logo" style="width:150px">"
aux_links:
  Github Repo: https://github.com/MichaelAkridge-NOAA/nmfs-opensci-container-images
footer_content: "<img src="https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true" alt="NMFS Open Science logo" style="width:150px"><br />NMFS Open Science (2023)"
