title: nmfs-opensci-container-images
description: nmfs-opensci-container-images using the Just the Docs theme!
theme: just-the-docs
color_scheme: wider
url: https://just-the-docs.github.io
aux_links:
  Template Repository: https://github.com/MichaelAkridge-NOAA/nmfs-opensci-container-images
