title: nmfs-opensci-container-images
description: nmfs-opensci-container-images using the Just the Docs theme!
theme: just-the-docs
url: https://michaelakridge-noaa.github.io/
logo: "/assets/images/nmfs-opensci-logo.png"
aux_links:
  Github Repo: https://github.com/MichaelAkridge-NOAA/nmfs-opensci-container-images
aux_links_new_tab: true
footer_content: "<img src="https://github.com/nmfs-opensci/assets/blob/main/logo/nmfs-opensci-logo2.png?raw=true" alt="NMFS Open Science logo" style="width:150px"><br />NMFS Open Science (2023)"
# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
