title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
color_scheme: wider
url: https://michaelakridge-noaa.github.io

aux_links:
  Template Repository: https://github.com/MichaelAkridge-NOAA/nmfs-opensci-container-images
